//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int ID { get; set; }
        public string answer1 { get; set; }
        public Nullable<bool> is_right { get; set; }
        public Nullable<int> scores { get; set; }
        public Nullable<int> result_id { get; set; }
    
        public virtual Result Result { get; set; }
    }
}
