//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_List
    {
        public int ID { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> training_id { get; set; }
        public System.DateTime register_date { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Training Training { get; set; }
    }
}
